### ISSUE TITLE
Can't get options to work

### ISSUE THREAD

**Issue by josdejong** [kristianmandrup/vue2-dragula#11]
I suppose I'm overlooking something obvious, but I simply can't get options to work.

I have a  vue2 project containing a simple drag and drop which allows reordering items in a list:

```html
<div id="drag-container" v-dragula="items" bag="items">
    <div v-for="(item, index) in item" :key="item.id" class="row">
        <div class="col drag-handle">
          <div class="drag-icon"></div>
        </div>

        ... item contents here ...
    </div>
</div>
```
Drag and drop works fine, but I want to allow dragging only via specific handle. I can use the `moves` option of dragula to control that, but I can't get it working in `vue2-dragula`. I tried things like:

```js
Vue.$dragula.$service.options('items', {
  moves: function (el, source, handle, sibling) {
    console.log('moves', el);
    return el.classList.contains('drag-handle')
  }
})
```

and 

```js
  beforeMount: function () {
    this.$dragula.$service.options('items', {
      moves: function (el, source, handle, sibling) {
        console.log('moves', el);
        return el.classList.contains('drag-handle')
      }
    })
  },
```
But the moves function is never invoked. Any idea what I'm overlooking?

**Comment by kristianmandrup** [comment]
TBH, I haven't tested the global `$service` api all that much

https://github.com/kristianmandrup/vue2-dragula/blob/master/src/vue-dragula.js#L93
https://github.com/kristianmandrup/vue2-dragula/blob/master/src/vue-dragula.js#L88
https://github.com/kristianmandrup/vue2-dragula/blob/master/src/vue-dragula.js#L9
https://github.com/kristianmandrup/vue2-dragula/blob/master/src/service.js#L148

```js
      // add default drake on global app service
      this.$service.options('default', {})
```

https://github.com/kristianmandrup/vue2-dragula/blob/master/src/service.js#L151

I'd recommend you go with the specific service instance API instead as demonstrated in the demo app. Try adding `moves` to one of those examples and see. Also, you can try to turn on logging.
I'm sadly not really an expert on all the `dragula` options themselves.

**Comment by josdejong** [comment]
Thanks for your fast response. 

I've tried to get these options applied via `createService` in all sorts of ways but no luck so far. Will continue tomorrow :(

**Comment by josdejong** [comment]
Ok managed to get it working (starting from one of the working examples from the demo app). The name of the service and drake should match with the created service, and the structure of the created service has to be correct.

```html
<div id="drag-container" v-dragula="items" service="itemsService" drake="items">
    <div v-for="(item, index) in item" :key="item.id" class="row">
        <div class="col drag-handle">
          <div class="drag-icon"></div>
        </div>

        ... item contents here ...
    </div>
</div>
```

```js
  created () {
    this.$dragula.createService({
      name: 'itemsService',
      drakes: {
        items: {
          moves: function (el, source, handle, sibling) {
            return handle.classList.contains('drag-handle')
          }
        }
      },
      options: {}
    })
  },
```

Thanks for your help Kristian.

**Comment by kristianmandrup** [comment]
Great to hear! I've added it to the new Wiki page with [usage examples](https://github.com/kristianmandrup/vue2-dragula/wiki/Usage-examples) 

Feel free to help improve the library and the docs!

**Comment by josdejong** [comment]
Just FYI: the app where I used `vue2-dragula` is now up and running, see https://tttimestamps.com :) 

thanks again.

**Comment by kristianmandrup** [comment]
Great!! Happy days :)

**Comment by liamcharmer** [comment]
Cannot read property 'createService' of undefined for me when the page is reloaded?

**Comment by kristianmandrup** [comment]
Look at the code samples that demonstrates how to use the APIs. Do the examples display the same malfunctioning behaviour on page reload?

Should be `this.$dragula.createService` used in the right context (ie. where this point to the plugin instance I believe)

I suggest you get together with some of the other devs who are using this library and start improving it, add unit tests etc. 

The [draghandlers](https://github.com/kristianmandrup/vue2-dragula/tree/draghandlers) is almost done and takes it in a much better direction... sadly I never got around to finish that refactoring.

Would be awesome if the  changes to master since branching off could be included in this `draghandlers` branch and then updated in general to work with Vue3 and the new proxies for change management. Always had an issue with how Vue notified when an array was modified.
