### ISSUE TITLE
Model undefined

### ISSUE THREAD

**Issue by SergeyMiracle** [kristianmandrup/vue2-dragula#19]
I have this simple code
```
<ol class="dd-list" v-dragula="items" drake="items">
        <li class="dd-item dd3-item" v-for="field in items" :key="field.id">
          <div class="dd-handle dd3-handle handle"></div>
          <div class="dd3-content"> {{ field.name }} </div>
        </li>
      </ol>
```
Almost everything is working, but models are always undefined - https://cl.ly/013K1m0A122x

My model from the start is empty array, but if i add manually data, it seems to work.
I can not see in docs, maybe i need to restart dragula after response from my server?

**Comment by kristianmandrup** [comment]
I really don't know. I never heard anyone else having this kind of problem. Yes, I see your model contains 2 undefined entries. Not sure why. I'd suggest you clone the master branch and `npm link` it in your project and debug from there. 

You can subclass the `ModelManager` and `ActionManager` classes to have more control, add more detailed logging etc.

You can also try [debugging from node with breakpoints in the browser](https://hackernoon.com/debug-node-js-with-chrome-devtools-aca7cf83af6b)

Hope that helps... I'm not currently developing more on this library so I rely on you guys to discover and fix any bugs/issues. Cheers.

**Comment by kristianmandrup** [comment]
Beware of Vue 2 reactivity issues when working with Arrays.

See post: [reactivity in Vue2 vs Vue3](https://blog.cloudboost.io/reactivity-in-vue-js-2-vs-vue-js-3-dcdd0728dcdf)

Use `Vue.set` or `vm.$set` to explicitly set/initialize an Array on a component and notify Vue about it.
