### ISSUE TITLE
Problem receiving data from server

### ISSUE THREAD

**Issue by renatosistemasvc** [kristianmandrup/vue2-dragula#20]
I'm trying to use vue2-dragula, but I'm not having the behavior I expect. I do not know what I'm doing wrong.

I'm using the library like this:

```
data: () => ({
        images: []
});
```
I get the data from the server and do this:

```
axios.get('myURL').then(response => {
                this.images = response.data;
})
```
And in my template I do this:

```
<div v-dragula="images" drake="images">
        <div class="ss-img-mini" v-for="(img, i) in images" :key="img.id">
                <img :src="img">
        </div>
</div>
```
My problem is that when I move an image, the new position is not reflected in the array images. I've identified that if I set the array images statically, everything works fine. But if the data arrives from the server, it does not work well. 

Does anyone know what can it be?

**Comment by kristianmandrup** [comment]
Sounds like the problem would be that you set the data at the wrong point in the component lifecycle. Why it works when you set it statically, coz there is no delay. You would have to share a full example of your component setup and play with life cycle methods.

**Comment by kristianmandrup** [comment]
Also, working with arrays in Vue (or most any reactive framework) is a bit tricky. You likely/might need to use `Vue.set` to make Vue react to the new data.

See this [article](https://blog.cloudboost.io/reactivity-in-vue-js-2-vs-vue-js-3-dcdd0728dcdf)

**Comment by renatosistemasvc** [comment]
you're right.
The problem is how the vue monitors the array.
I tested the Vue.set and the problem was solved.
thank you so much.

**Comment by kristianmandrup** [comment]
Great! I'm sure plenty of ppl run into this issue.
I would very much welcome a page with an example in the project wiki. 
Cheers!
