### ISSUE TITLE
ReferenceError: msg is not defined

### ISSUE THREAD

**Issue by rikard-io** [kristianmandrup/vue2-dragula#23]
Tiny bug which is fixed in the source (service.js:116). Just need to update the dist file so we get the update when we install the npm package.

Cheers!

**Comment by kristianmandrup** [comment]
Could you make a PR with entire fix incl. dist, thanks

**Comment by nailliK** [comment]
Any word on a fix/release for this?

**Comment by rikard-io** [comment]
@nailliK @kristianmandrup tried to build it and after fixing a few dependency issues I still got quite a few errors when trying to run the the compiled script (tested it by running the example given in this repo). 

Might be better if someone more familiar with the code and recent updates would take a look. Not sure if it's the lib that is broken or the example that is outdated.

**Comment by kristianmandrup** [comment]
Will take a look ASAP.  Sorry. For now try using previous release

**Comment by kristianmandrup** [comment]
Published `vue2-dragula@2.5.1` with latest `dist`
