### ISSUE TITLE
2.5.1 will have error 

### ISSUE THREAD

**Issue by tonyisid** [kristianmandrup/vue2-dragula#24]
Cannot read property 'copy' of undefined.

**Comment by sempixel** [comment]
Reverted to 2.5.0 as well as I get an `opts.drake is undefined` at page load.

**Comment by kristianmandrup** [comment]
Okay. Will fix. Thanks

**Comment by kristianmandrup** [comment]
Fixed and pushed 2.5.2 to master. Please confirm fix, then will make release.

**Comment by sempixel** [comment]
It works on 2.5.4. Thanks.
