### ISSUE TITLE
Dragging video stops playback

### ISSUE THREAD

**Issue by rostopira** [kristianmandrup/vue2-dragula#34]
I have few `<video>` components with WebRTC streams in flexbox, and I want them to be dnd-ed freely
It works, but video stop playing when I do it
```
      <div style="display: flex; flex-wrap: wrap" v-dragula="activeConnections" drake="first">
        <video 
          v-for="conn in activeConnections"
          :id="conn.id"
          muted autoplay
        ></video>
      </div>
```

**Comment by kristianmandrup** [comment]
I would assume this is standard browser behaviour? Perhaps just have it start playing again when you confirm the drop target (action handler)? Note that I'm not using Vue anymore and looking for someone to take over the steering and further development of this library.

**Comment by rostopira** [comment]
Thanks for quick response and advice
I've got this working with following code

```
var vueApp = new Vue({
    el: '#app',
    data: {
        firebaseUid: null,
        activeConnections: []
    },
    created() {
        console.log("created");
        const service = Vue.$dragula.$service;
        service.eventBus.$on("dragend", args => {
            let element = args.el;
            if (element instanceof HTMLVideoElement) {
                element.play();
            }
        });
    }
});
```

**Comment by kristianmandrup** [comment]
Yeah, cool, perfect! Exactly the way it should be done I imagine :) Great stuff!!!
