### ISSUE TITLE
Copying issues

### ISSUE THREAD

**Issue by runrog** [kristianmandrup/vue2-dragula#6]
I'm curious if anyone has encountered this issue. I can't seem to find the root cause yet. I have a component with 2 droppable containers. Like so:
```
<div class="myComponent">
  <div class="container" v-dragula drake="first" service="first-service">
      <div class="drag-test">Test item</div>
      <div class="drag-test">Test item</div>
  </div>
  <div class="container" v-dragula drake="first" service="first-service">
      <div class="drag-test">Test item</div>
      <div class="drag-test">Test item</div>
  </div>
</div>
```
And I have a service setup like this inside of my created() function:
```
const myService = Vue.$dragula.createService({
   name: 'first-service',
     drakes: {
        first: {
          copy: true,
       },
   },
});
```
The copying is working however when trying to drop into one of the containers, I keep getting the following error:
```
Uncaught SyntaxError: Unexpected token u in JSON at position 0
```
Any ideas? Thanks!

**Comment by SimplyCorey** [comment]
I'm having the exact same issue with the `copy` option and can not find a solution.

**Comment by kristianmandrup** [comment]
Hey guys, 

I'm sorry I haven't worked on this project lately. I will get "back to business" ASAP.
You are of course welcome to checkout the repo and make your own improvements, patching or bug fixing as needed and then make a PR.

The `copy` option should work for one or more of the examples in the demo app.

**Comment by SimplyCorey** [comment]
Here is some more information.  I will open up a pull request if I am able to solve it

```
Uncaught SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at DragHandler.jsonDropElmModel (eval at <anonymous> (), <anonymous>:1487:20)
    at DragHandler.dropModelTarget (eval at <anonymous> (), <anonymous>:1384:64)
    at DragHandler.dropModel (eval at <anonymous> (), <anonymous>:1406:56)
    at DragHandler.drop (eval at <anonymous> (), <anonymous>:1467:13)
    at emitter (eval at <anonymous> ()
    at Array.forEach (native)
    at Object.eval (eval at <anonymous> (), <anonymous>:131:13)
    at Object.thing.emit (eval at <anonymous> (), <anonymous>:121:51)
    at drop (eval at <anonymous> (), <anonymous>:683:16)
```

**Comment by kristianmandrup** [comment]
http://stackoverflow.com/questions/13022178/uncaught-syntaxerror-unexpected-token-u-json

That error is normally seen when the value given to JSON.parse is actually undefined. 
So, I would check the code that is trying to parse this in `DragHandler.jsonDropElmModel`, make a check for null, undefined etc and then act accordingly

**Comment by SimplyCorey** [comment]
I think where I am going wrong is using the v-dragula directive.  I have it set to point to an array within my data object, but it doesn't seem to grab it as the model.  Am I not setting this correctly?
```
        data () {
            return {
                query: null,
                rules: [],
            }
        },
```

```
<div class="col-md-2" v-dragula="rules" drake="query-builder">
...
</div>
```

**Comment by runrog** [comment]
If I can find a solution I'll open a PR. I believe Dragula is whats doing the parsing, I'm not really doing anything else other than setting up just 2 containers and testing the copy function. I tried using the normal Dragula plugin as a new directive and the copying/dropping is working fine. Also, in the demo, the copying is working but is a little buggy. After a few drops it starts erroring out as well.

**Comment by kristianmandrup** [comment]
Please have a look at the demo examples: https://github.com/kristianmandrup/vue2-dragula-demo/

**Comment by SimplyCorey** [comment]
I'm getting the same error using the demo

**Comment by kristianmandrup** [comment]
I will look at this issue tonight or this weekend.

**Comment by SimplyCorey** [comment]
@kristianmandrup Thanks, I tried to find a fix for it but I have been unable to.  If I do, I'll open a pull request.

**Comment by kristianmandrup** [comment]
I will have a look tonight. Which of the examples in the demo is failing? How can I duplicate/cause this error?

**Comment by kristianmandrup** [comment]
I think I completely understand the problem. Currently the model manager is designed for move by default, not copy.  You have to supply your own manager or we need to change the default one to use the dragula copy setting for copy behavior. Also see latest branch

**Comment by kristianmandrup** [comment]
I tried to make this fix

https://github.com/kristianmandrup/vue2-dragula/tree/copy-fix

Didn't test it yet however, but shows the general gist of a solution I think

**Comment by SimplyCorey** [comment]
@kristianmandrup I will take a look at the patch this weekend.  Thanks for your help!

**Comment by kristianmandrup** [comment]
Great! I would also like to finish the work I did on improving/separating logic for [draghandlers](https://github.com/kristianmandrup/vue2-dragula/tree/draghandlers) etc. sometime soon...

**Comment by kristianmandrup** [comment]
I've just tested `Named Services` example in the [vue2 demo app](https://github.com/kristianmandrup/vue2-dragula-demo/)

No error in console and elements are copied from each container as expected.
I then tried `npm link` to the `copy-fix` branch and it also worked as expected!

Merged `copy-fix` branch with master and updated demo app with note on example using drake setting `copy:true`

Service config:

```js
    dragula.createService({
      name: 'first',
      drakes: {
        first: {
          copy: true
        }
      },
      options: {
        logging: {
          dragHandler: true
        }
      }
    })
```

The template config:

```html
      <div class="parent">
        <label>Named Services example</label>
        <div class="wrapper">
          <div class="container" v-dragula="colOne" service="my-first" drake="first">
            <div v-for="text in colOne" @click="onClick">{{text}} [click me]</div>
          </div>
          <div class="container" v-dragula="colTwo" service="my-first" drake="first">
            <div v-for="text in colTwo">
              <span class="handle">+</span>
              <span>{{text}}</text>
            </div>
          </div>
        </div>
        <h4>Result</h5>
        <p>
          <h5>colOne</h5>
          <div v-for="text in colOne">{{text}}</div>
        </p>

        <p>
          <h5>colTwo</h5>
          <div v-for="text in colTwo">{{text}}</div>
        </p>
      </div>
    </div>
```

**Comment by kristianmandrup** [comment]
Will await confirmation from one of you guys before making this a new release

**Comment by SimplyCorey** [comment]
@kristianmandrup It is now working, thanks for your help!

**Comment by kristianmandrup** [comment]
@SimplyCorey Great to hear!
