### ISSUE TITLE
i want aply this code, help please 

### ISSUE THREAD

**Issue by oteroweb** [kristianmandrup/vue2-dragula#9]
https://github.com/valor-software/ng2-dragula/issues/282

constructor(private dragulaService: DragulaService) {
    //setup dragNdrop for creating content
    dragulaService.setOptions('page-bag', {
      copy: function (el, source) {
        // To copy only elements in left container, the right container can still be sorted
        return source.id === 'left';
      },
      copySortSource: false,
      accepts: function(el, target, source, sibling) {
        // To avoid draggin from right to left container
        return target.id !== 'left';
      }
    })
  }

**Comment by kristianmandrup** [comment]
I don't understand what you are trying to do or how this plugin is involved? If you are using my plugin, I recommend you debug by linking to a local repo clone using `npm link`
